def f1 = new File('target/site/images/overview.png')
f1.deleteOnExit()
def f2 = new File('a/target/site/images/overview.png')
f2.deleteOnExit()
def f3 = new File('b/target/site/images/overview.png')
f3.deleteOnExit()
def f4 = new File('c/target/site/images/overview.png')
f4.deleteOnExit()
